### ISSUE TITLE
Problems with running addon on recent milhouse builds.

### ISSUE THREAD

**Issue by laric** [LS80/script.libreelec.devupdater#1]
I am trying to run it on the new milhouse builds that are failing to start the addon.
Here is an exceprt from the log.
`12:11:58.687 T:139940365387520    INFO: initializing python engine.
12:11:58.687 T:139940365387520   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/script.libreelec.devupdater/default.py): start processing
12:11:58.705 T:139940365387520   DEBUG: -->Python Interpreter Initialized<--
12:11:58.705 T:139940365387520   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/script.libreelec.devupdater/default.py): the source file to load is "/storage/.kodi/addons/script.libreelec.devupdater/default.py"
12:11:58.706 T:139940365387520   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/script.libreelec.devupdater/default.py): setting the Python path to /storage/.kodi/addons/script.libreelec.devupdater:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.html2text/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
12:11:58.706 T:139940365387520   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/script.libreelec.devupdater/default.py): entering source directory /storage/.kodi/addons/script.libreelec.devupdater
12:11:58.706 T:139940365387520   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/script.libreelec.devupdater/default.py): instantiating addon using automatically obtained id of "script.libreelec.devupdater" dependent on version 2.13.0 of the xbmc.python api
12:11:58.920 T:139940365387520 WARNING: CSkinInfo: failed to load skin settings
12:11:58.938 T:139942993862144   DEBUG: Activating window ID: 10138
12:11:58.938 T:139942993862144   DEBUG: ------ Window Init (DialogBusy.xml) ------
12:11:59.053 T:139940365387520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'LibreELEC-9.0'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 398, in <module>
                                                main.start()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 78, in start
                                                self.select_build()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 104, in select_build
                                                build_select = gui.BuildSelectDialog(self.installed_build)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 79, in __init__
                                                self._builds = self._get_build_links(self._build_url)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/utils.py", line 90, in busy_wrapper
                                                return f(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 212, in _get_build_links
                                                links = build_url.builds()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 268, in builds
                                                return sorted(self._extractor(self.url), reverse=True)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 208, in __iter__
                                                releases = self._json()[libreelec.release()]['project'][config.arch]['releases']
                                            KeyError: 'LibreELEC-9.0'
                                            -->End of Python script error report<--
12:11:59.055 T:139942993862144   DEBUG: ------ Window Init (DialogNotification.xml) ------
12:11:59.111 T:139940365387520    INFO: Python script stopped
12:11:59.112 T:139940365387520   DEBUG: Thread LanguageInvoker 139940365387520 terminating
12:11:59.182 T:139942993862144   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
12:12:04.894 T:139942993862144   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
`

**Comment by MusterGit** [comment]
I have the same problem. As far as I understand the bug, it's because there is no official LibreELEC-9.0 build yet. No matter what release source you use (in our case Milhouse), the addon always tries to retrieve the list of official releases first. So this process stops with the error mentioned above and breaks the addon.

**Comment by MusterGit** [comment]
A temporary fix is to comment out lines 12 and 13 of file script.libreelec.devupdater\resources\lib\sources.py. Delete the file sources.pyo and start the addon afterwards.

**Comment by Mike-KL** [comment]
Was not aware you had updated ;-) addon for libreelec, Installed addon on #0408 millhouse build for rpi2 today and like others I am unable to sucessfully start/use addon as it errors and will not start!

kodi debug log https://pastebin.com/t8bpGbzx

**Comment by MusterGit** [comment]
I'm not the author, just a user that found a workaround. Try the modification I mentioned above and you will be able to use the addon again.

**Comment by Mike-KL** [comment]
@MusterGit Thanks for workaround, I made suggested modifications (commented out lines 12 & 13 in sources.py and deleted sources.pyo) and working fine now for download/installation of milhouse nightly Leia builds

**Comment by HPMSGEN8** [comment]
Thanks alot for this temp fix BUT i do not get anything anymore on the list the App loads and that is it any advice ?

**Comment by ManuStrozor** [comment]
Fixed with the last pull request
