### ISSUE TITLE
Updater is crashing at start

### ISSUE THREAD

**Issue by hbbernardo** [LS80/script.libreelec.devupdater#10]
Since two days my LibreELEC Dev Updater is crashing at start. 

I went thru the logs and found this:

21:04:17.412 T:1432331120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'committer'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 398, in <module>
                                                main.start()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 78, in start
                                                self.select_build()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 104, in select_build
                                                build_select = gui.BuildSelectDialog(self.installed_build)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 79, in __init__
                                                self._builds = self._get_build_links(self._build_url)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/utils.py", line 90, in busy_wrapper
                                                return f(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 212, in _get_build_links
                                                links = build_url.builds()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 271, in builds
                                                return sorted(self._extractor(self.url), reverse=True)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 215, in __iter__
                                                release_link = ReleaseLink(base_url, filename, release_name)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 152, in __init__
                                                Release.__init__(self, release)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 81, in __init__
                                                self.release_date = self.get_release_date()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 97, in get_release_date
                                                return commit['committer']['date']
                                            KeyError: 'committer'
                                            -->End of Python script error report<--

I am running the latest LibreELEC Leia TestBuild from today (8th of December) and Dev Updater 5.1.2.

I hope that helps to shed some light into this issue.

**Comment by Smultie** [comment]
Sorta got the same problem:
19:17:12.642 T:1290781552 WARNING: addons must not activate DialogBusy
19:17:16.962 T:1290781552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'committer'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 398, in <module>
                                                main.start()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 78, in start
                                                self.select_build()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 104, in select_build
                                                build_select = gui.BuildSelectDialog(self.installed_build)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 79, in __init__
                                                self._builds = self._get_build_links(self._build_url)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/utils.py", line 90, in busy_wrapper
                                                return f(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 212, in _get_build_links
                                                links = build_url.builds()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 271, in builds
                                                return sorted(self._extractor(self.url), reverse=True)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 215, in __iter__
                                                release_link = ReleaseLink(base_url, filename, release_name)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 152, in __init__
                                                Release.__init__(self, release)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 81, in __init__
                                                self.release_date = self.get_release_date()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 97, in get_release_date
                                                return commit['committer']['date']
                                            KeyError: 'committer'
                                            -->End of Python script error report<--

**Comment by Smultie** [comment]
calling @LS80  !!

**Comment by zecompadre** [comment]
calling @LS80 !!

**Comment by LS80** [comment]
I'm now seeing the error. I wasn't using LibreELEC for a while and couldn't reproduce any issues when I ran it outside of Kodi. I should have some time in the next few days to investigate what Kodi change has broken it.

**Comment by Smultie** [comment]
@LS80 , need more info?

**Comment by Smultie** [comment]
Well?

**Comment by Smultie** [comment]
@LS80 are you there mate?

**Comment by LS80** [comment]
Yes just short of time. You can use the command line instead by the way.

ssh to LibreELEC and run `./devupdate`.

**Comment by Smultie** [comment]
LibreELEC:~ # ./devupdate download
[0] Official Releases
[1] Milhouse Builds
[2] Milhouse Builds (debug)
--------------------------------------------------
Choose an item or "q" to quit: 1

Arch: RPi2.arm
Traceback (most recent call last):
  File "./devupdate", line 203, in <module>
    args.func(args)
  File "./devupdate", line 133, in download
    print "Installed build: {}".format(installed_build)
  File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 56, in __str__
    return '{} ({})'.format(self.version, self.date)
  File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 69, in version
    return self._version
AttributeError: 'Release' object has no attribute '_version'
