### ISSUE TITLE
Script v5.1.2 broken.. 

### ISSUE THREAD

**Issue by Cris--** [LS80/script.libreelec.devupdater#11]
Hi,

after some LibreElec milhouse releases (maybe #203) the updater doesn't work anymore:

09:28:01.017 T:1395680112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'BuildSelectDialog' object has no attribute '_selected_source'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 398, in <module>
                                                main.start()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 78, in start
                                                self.select_build()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 107, in select_build
                                                self.selected_source = build_select.selected_source
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 127, in selected_source
                                                return self._selected_source
                                            AttributeError: 'BuildSelectDialog' object has no attribute '_selected_source'
                                            -->End of Python script error report<--

Hope it gets fixed leo!

**Comment by LS80** [comment]
I'll have a look...

**Comment by f1vefour** [comment]
Same issue, it's indeed broken currently.

**Comment by EgorOA** [comment]
Same trouble(((

**Comment by zecompadre** [comment]
any solution ?

**Comment by peat80** [comment]
I think its dead. Nobody cares to fix it. Sad, but true. 
Have it deinstalled now and use the libreelec-settings-addon to update.

**Comment by zecompadre** [comment]
calling @LS80 !!
