### ISSUE TITLE
Error on 5.1.3

### ISSUE THREAD

**Issue by Megachip** [LS80/script.libreelec.devupdater#12]
```
2019-03-25 22:36:19.050 T:1698481008 WARNING: Previous line repeats 6 times.                                                                                                                                
2019-03-25 22:36:19.051 T:1698481008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                           
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                                                
                                            Error Type: <type 'exceptions.AttributeError'>                                                                                                                  
                                            Error Contents: 'Release' object has no attribute '_version'                                                                                                    
                                            Traceback (most recent call last):                                                                                                                              
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 392, in <module>                                                                    
                                                utils.maybe_confirm_installation(selected, installed_build)                                                                                                 
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/utils.py", line 190, in maybe_confirm_installation                                      
                                                log.log("Installed build: {}".format(installed_build))                                                                                                      
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 56, in __str__                                                         
                                                return '{} ({})'.format(self.version, self.date)                                                                                                            
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 69, in version                                                         
                                                return self._version                                                                                                                                        
                                            AttributeError: 'Release' object has no attribute '_version'                                                                                                    
                                            -->End of Python script error report<--                                                                                                                         
2019-03-25 22:36:24.754 T:1414271856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                           
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                                                
                                            Error Type: <type 'exceptions.AttributeError'>                                                                                                                  
                                            Error Contents: 'Release' object has no attribute '_datetime'                                                                                                   
                                            Traceback (most recent call last):                                                                                                                              
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 386, in <module>                                                                    
                                                new_build_check()                                                                                                                                           
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 350, in new_build_check                                                             
                                                if latest and latest > installed_build:                                                                                                                     
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 53, in __gt__                                                          
                                                return self._datetime > other._datetime                                                                                                                     
                                            AttributeError: 'Release' object has no attribute '_datetime'                                                                                                   
                                            -->End of Python script error report<--  
```

**Comment by LS80** [comment]
Could you attach the full log file please.

**Comment by Megachip** [comment]
@LS80 that was all in this timespan ... but will recheck
