### ISSUE TITLE
Errors On Builds v8.1.x

### ISSUE THREAD

**Issue by HPMSGEN8** [LS80/script.libreelec.devupdater#3]
Hi,

The Add-On is failing on the builds v8.1.x. Can you take an look please. 

Thanks

`00:32:06.516 T:3447452576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: 
                                            Error Contents: 'LibreELEC-8.2'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 398, in 
                                                main.start()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 78, in start
                                                self.select_build()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/default.py", line 104, in select_build
                                                build_select = gui.BuildSelectDialog(self.installed_build)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 79, in __init__
                                                self._builds = self._get_build_links(self._build_url)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/utils.py", line 90, in busy_wrapper
                                                return f(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/gui.py", line 212, in _get_build_links
                                                links = build_url.builds()
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 268, in builds
                                                return sorted(self._extractor(self.url), reverse=True)
                                              File "/storage/.kodi/addons/script.libreelec.devupdater/resources/lib/builds.py", line 208, in __iter__
                                                releases = self._json()[libreelec.release()]['project'][config.arch]['releases']
                                            KeyError: 'LibreELEC-8.2'
                                            -->End of Python script error report<--`

**Comment by Megachip** [comment]
Same on 9.X Builds :(

**Comment by ManuStrozor** [comment]
This problem is fixed with my recent changes in the last pull request that i made
